# Generated by Django 2.0.4 on 2018-05-01 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('asin', models.CharField(help_text='ASIN for the product', max_length=50, primary_key=True, serialize=False, verbose_name='ASIN')),
                ('asin_name', models.CharField(blank=True, help_text='ASIN Name for the product', max_length=200, null=True, verbose_name='ASIN Name')),
                ('warehouse_units', models.IntegerField(blank=True, help_text='Units stored at Amazon Warehouse', null=True)),
                ('external_id', models.CharField(blank=True, help_text='External ID', max_length=200, null=True)),
                ('released', models.DateField(blank=True, help_text='Date Released', null=True)),
                ('list_price', models.FloatField(blank=True, help_text='List Price', null=True)),
                ('product_group', models.CharField(blank=True, help_text='Product Group', max_length=200, null=True)),
                ('category', models.CharField(blank=True, help_text='Category', max_length=100, null=True)),
                ('sub_category', models.CharField(blank=True, help_text='Sub Category', max_length=150, null=True)),
                ('model_number', models.CharField(blank=True, help_text='Model Number', max_length=150, null=True)),
                ('catalog_number', models.CharField(blank=True, help_text='Catalog Number', max_length=150, null=True)),
                ('replenishment_code', models.CharField(blank=True, help_text='Replenishment Code', max_length=150, null=True)),
                ('page_view_rank', models.IntegerField(blank=True, help_text='Page View Rank', null=True)),
                ('brand_code', models.CharField(blank=True, help_text='Brand Code', max_length=50, null=True)),
                ('vendor', models.CharField(help_text='Vendor', max_length=50)),
            ],
            options={
                'permissions': (('can_input_data', 'Able to Input Data'),),
            },
        ),
    ]
