# Generated by Django 2.0.4 on 2018-05-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headers',
            fields=[
                ('amazon_header', models.CharField(help_text='Amazon CSV Header', max_length=200, primary_key=True, serialize=False, verbose_name='Amazon Header')),
                ('database_header', models.CharField(help_text='Database Header', max_length=200, verbose_name='Database Header')),
            ],
            options={
                'permissions': (('can_add_new_headers', 'Able to Amend Amazon Database Headers'),),
            },
        ),
    ]
