# Generated by Django 2.0.4 on 2018-05-02 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checks',
            fields=[
                ('amazon_header', models.CharField(help_text='Amazon CSV Header', max_length=200, primary_key=True, serialize=False, verbose_name='Amazon Header')),
                ('file_type', models.CharField(help_text='File', max_length=200, verbose_name='File Type')),
            ],
            options={
                'permissions': (('can_add_new_checks', 'Able to Amend Amazon Database Checks'),),
            },
        ),
    ]
