# Generated by Django 2.0.4 on 2018-05-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0005_salesdiagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesdiagnostic',
            name='asin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reporting.Products'),
        ),
    ]
