# Generated by Django 2.0.4 on 2018-05-03 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0006_auto_20180503_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdiagnostic',
            name='products',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='reporting.Products'),
        ),
        migrations.AlterField(
            model_name='salesdiagnostic',
            name='asin',
            field=models.CharField(help_text='ASIN for the product', max_length=50, verbose_name='ASIN'),
        ),
    ]
