# Generated by Django 2.0.4 on 2018-05-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0007_auto_20180503_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdiagnostic',
            name='product_name',
            field=models.CharField(blank=True, help_text='ASIN Name for the product', max_length=200, null=True, verbose_name='Product Name'),
        ),
    ]
