# Generated by Django 2.0.4 on 2018-05-04 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0008_salesdiagnostic_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesdiagnostic',
            name='products',
        ),
    ]
