# Generated by Django 2.0.4 on 2018-05-07 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0010_auto_20180505_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryHealth',
            fields=[
                ('asin', models.CharField(help_text='ASIN for the product', max_length=50, verbose_name='ASIN')),
                ('date', models.DateField(help_text='Date Released')),
                ('asin_date', models.CharField(help_text='ASIN_Date Combo for the entry', max_length=50, primary_key=True, serialize=False, verbose_name='ASIN_Date Combined')),
                ('product_name', models.CharField(blank=True, help_text='ASIN Name for the product', max_length=200, null=True, verbose_name='Product Name')),
                ('net_received', models.DecimalField(blank=True, decimal_places=2, help_text='Net Received Money', max_digits=14, null=True)),
                ('net_received_units', models.IntegerField(blank=True, help_text='Net Received Units', null=True)),
                ('sell_through_rate', models.DecimalField(blank=True, decimal_places=5, help_text='Sell-Through Rate', max_digits=8, null=True)),
                ('open_purchase_oq', models.IntegerField(blank=True, help_text='Open Purchase Order Quantity', null=True)),
                ('sellable_oh_inven', models.DecimalField(blank=True, decimal_places=2, help_text='Sellable On Hand Inventory', max_digits=14, null=True)),
                ('sellable_oh_inven_trail', models.DecimalField(blank=True, decimal_places=2, help_text='Sellable On Hand Inventory - Trailing 30-day Average', max_digits=14, null=True)),
                ('sellable_oh_units', models.IntegerField(blank=True, help_text='Sellable On Hand Units', null=True)),
                ('unsellable_oh_inven', models.DecimalField(blank=True, decimal_places=2, help_text='Unsellable On Hand Inventory', max_digits=14, null=True)),
                ('unsellable_oh_inven_trail', models.DecimalField(blank=True, decimal_places=2, help_text='Unsellable On Hand Inventory - Trailing 30-day Average', max_digits=14, null=True)),
                ('unsellable_oh_units', models.IntegerField(blank=True, help_text='Unsellable On Hand Units', null=True)),
                ('aged_90_sellable', models.DecimalField(blank=True, decimal_places=2, help_text='Aged 90+ Days Sellable Inventory', max_digits=14, null=True)),
                ('aged_90_sellable_trail', models.DecimalField(blank=True, decimal_places=2, help_text='Aged 90+ Days Sellable Inventory - Trailing 30-day Average', max_digits=14, null=True)),
                ('aged_90_sellable_units', models.IntegerField(blank=True, help_text='Aged 90+ Days Sellable Units', null=True)),
                ('repl_category', models.CharField(help_text='Replenishment Category', max_length=70)),
            ],
            options={
                'permissions': (('can_input_data', 'Able to Input Data'),),
            },
        ),
        migrations.AlterField(
            model_name='salesdiagnostic',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='reporting.Product'),
        ),
    ]
