# Generated by Django 2.0.4 on 2018-05-08 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0011_auto_20180507_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredProduct',
            fields=[
                ('start_date', models.DateField(help_text='Start Date of Campaign')),
                ('end_date', models.DateField(help_text='End Date of Campaign')),
                ('currency', models.CharField(blank=True, help_text='Currency', max_length=10, null=True)),
                ('campaign_name', models.CharField(blank=True, help_text='Campaign Name', max_length=150, null=True)),
                ('asin', models.CharField(help_text='Campaign Name', max_length=150)),
                ('impressions', models.IntegerField(blank=True, help_text='Impressions', null=True)),
                ('clicks', models.IntegerField(blank=True, help_text='Clicks', null=True)),
                ('ctr', models.DecimalField(blank=True, decimal_places=5, help_text='Click-Thru Rate (CTR)', max_digits=8, null=True)),
                ('cpc', models.DecimalField(blank=True, decimal_places=5, help_text='Cost Per Click (CPC)', max_digits=8, null=True)),
                ('spend', models.DecimalField(blank=True, decimal_places=5, help_text='Spend', max_digits=8, null=True)),
                ('f_day_sales', models.DecimalField(blank=True, decimal_places=2, help_text='Spend', max_digits=11, null=True)),
                ('acos', models.DecimalField(blank=True, decimal_places=5, help_text='Total Advertising Cost of Sales (ACoS)', max_digits=8, null=True)),
                ('raos', models.DecimalField(blank=True, decimal_places=2, help_text='Total Return on Advertising Spend (RoAS)', max_digits=8, null=True)),
                ('f_day_orders', models.IntegerField(blank=True, help_text='14 Day Total Orders (#)', null=True)),
                ('f_day_units', models.IntegerField(blank=True, help_text='14 Day Total Units (#)', null=True)),
                ('f_day_conv_rate', models.DecimalField(blank=True, decimal_places=2, help_text='14 Day Conversion Rate', max_digits=8, null=True)),
                ('campasin', models.CharField(help_text='Campaign Name ASIN Combo', max_length=150, primary_key=True, serialize=False)),
            ],
            options={
                'permissions': (('can_input_data', 'Able to Input Data'),),
            },
        ),
    ]
