# Generated by Django 2.0.4 on 2018-05-09 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0012_sponsoredproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryForecast',
            fields=[
                ('asin', models.CharField(help_text='ASIN for the product', max_length=50, verbose_name='ASIN')),
                ('date', models.DateField(help_text='Date Released')),
                ('asin_date', models.CharField(help_text='ASIN_Date Combo for the entry', max_length=50, primary_key=True, serialize=False, verbose_name='ASIN_Date Combined')),
                ('week_forecast', models.IntegerField(blank=True, help_text='Weekly Inventory Forecast', null=True)),
                ('week2_forecast', models.IntegerField(blank=True, help_text='Next Weeks Inventory Forecast', null=True)),
                ('week3_forecast', models.IntegerField(blank=True, help_text='3 Weeks Out Inventory Forecast', null=True)),
                ('week4_forecast', models.IntegerField(blank=True, help_text='4 Weeks Out Inventory Forecast', null=True)),
                ('week5_forecast', models.IntegerField(blank=True, help_text='5 Weeks Out Inventory Forecast', null=True)),
            ],
            options={
                'permissions': (('can_input_data', 'Able to Input Data'),),
            },
        ),
    ]
