# Generated by Django 2.0.4 on 2018-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0013_inventoryforecast'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='asin_name',
        ),
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, help_text='ASIN Name for the product', max_length=200, null=True, verbose_name='Product Name'),
        ),
    ]
